# Boilerplate
from command_center import *

# Keyboard bug out fixes
# key_up('LSHIFT')
# raise SystemExit(0)

# Loading Wait
print ('glhf')
time.sleep(5)

exit_menu()

start_routine()
time.sleep(4)
worker()
time.sleep(7)
overlord()
time.sleep(20)
spawning_pool()
time.sleep(2)
worker()
time.sleep(3)
worker()
time.sleep(3)
worker()
time.sleep(3)
zergling()
time.sleep(35)
queen()
zergling()
zergling()
zergling()
time.sleep(9)
overlord()
time.sleep(9)
zergling()
time.sleep(9)
zergling()
time.sleep(9)
screen_drag_select()
add_to_hotkey(hk_master)
extra_tabs = True
brute_force_attack()
for x in range(0, 10):
    queen(extra_tabs)
    inject()
    overlord(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    overlord(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    time.sleep(9)
    zergling(extra_tabs)
    screen_drag_select()
    add_to_hotkey(hk_master)
    brute_force_attack()
gg()

# surrender()
